# Generated by Django 6.1.1 on 2026-09-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_dietary_flags_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
