# Generated by Django 6.1.1 on 2026-09-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_promocode_rename_customer_order_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('courier_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('courier_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('courier_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('polyline_route', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order')),
            ],
        ),
    ]
